### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by ryanerwin** [fredcox/crazydiskmark#4]
When running Crazy DiskMark 0.2.45 I'm getting the following...
Also note that the 3rd and 4th line of the test never complete:

![image](https://user-images.githubusercontent.com/2156415/89022122-b7ed1f80-d34b-11ea-8939-c6456a283cc8.png)

```
2020-07-31 16:31:33 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/seq1mq8t1read.sh /tmp/sdb1]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/home/ryan/.local/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1115, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ryan/.local/bin/crazydiskmark", line 16, in <module>
    app.exec_()
  File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 62, in threadFinished
    self.signal.emit(self.bw_bytes)
  File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 178, in receiveThreadfinish
    self.logger.info('Receiving signal ok ', val)
Message: 'Receiving signal ok '
Arguments: ('174.03 MB/s',)
2020-07-31 16:31:46 ri9 crazydiskmark[1322493] INFO Finished QThread operationIndex = 0
2020-07-31 16:31:46 ri9 crazydiskmark[1322493] INFO Running Thread [1] Even? False
2020-07-31 16:31:46 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/seq1mq8t1write.sh /tmp/sdb1]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/home/ryan/.local/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1115, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ryan/.local/bin/crazydiskmark", line 16, in <module>
    app.exec_()
  File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 62, in threadFinished
    self.signal.emit(self.bw_bytes)
  File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 178, in receiveThreadfinish
    self.logger.info('Receiving signal ok ', val)
Message: 'Receiving signal ok '
Arguments: ('187.49 MB/s',)
2020-07-31 16:31:53 ri9 crazydiskmark[1322493] INFO Finished QThread operationIndex = 1
2020-07-31 16:31:53 ri9 crazydiskmark[1322493] INFO Running Thread [2] Even? True
2020-07-31 16:31:53 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/seq1mq1t1read.sh /tmp/sdb1]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/home/ryan/.local/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1115, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ryan/.local/bin/crazydiskmark", line 16, in <module>
    app.exec_()
  File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 62, in threadFinished
    self.signal.emit(self.bw_bytes)
  File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 178, in receiveThreadfinish
    self.logger.info('Receiving signal ok ', val)
Message: 'Receiving signal ok '
Arguments: ('175.05 MB/s',)
2020-07-31 16:32:06 ri9 crazydiskmark[1322493] INFO Finished QThread operationIndex = 2
2020-07-31 16:32:06 ri9 crazydiskmark[1322493] INFO Running Thread [3] Even? False
2020-07-31 16:32:06 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/seq1mq1t1write.sh /tmp/sdb1]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/home/ryan/.local/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1115, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ryan/.local/bin/crazydiskmark", line 16, in <module>
    app.exec_()
  File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 62, in threadFinished
    self.signal.emit(self.bw_bytes)
  File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 178, in receiveThreadfinish
    self.logger.info('Receiving signal ok ', val)
Message: 'Receiving signal ok '
Arguments: ('187.1 MB/s',)
2020-07-31 16:32:12 ri9 crazydiskmark[1322493] INFO Finished QThread operationIndex = 3
2020-07-31 16:32:12 ri9 crazydiskmark[1322493] INFO Running Thread [4] Even? True
2020-07-31 16:32:12 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/rnd4kq32t16read.sh /tmp/sdb1]
```

**Comment by fredcox** [comment]
> When running Crazy DiskMark 0.2.45 I'm getting the following...
> Also note that the 3rd and 4th line of the test never complete:
> 
> ![image](https://user-images.githubusercontent.com/2156415/89022122-b7ed1f80-d34b-11ea-8939-c6456a283cc8.png)
> 
> ```
> 2020-07-31 16:31:33 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/seq1mq8t1read.sh /tmp/sdb1]
> --- Logging error ---
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
>     msg = self.format(record)
>   File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
>     return fmt.format(record)
>   File "/home/ryan/.local/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1115, in format
>     return logging.Formatter.format(self, record)
>   File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
>     record.message = record.getMessage()
>   File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "/home/ryan/.local/bin/crazydiskmark", line 16, in <module>
>     app.exec_()
>   File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 62, in threadFinished
>     self.signal.emit(self.bw_bytes)
>   File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 178, in receiveThreadfinish
>     self.logger.info('Receiving signal ok ', val)
> Message: 'Receiving signal ok '
> Arguments: ('174.03 MB/s',)
> 2020-07-31 16:31:46 ri9 crazydiskmark[1322493] INFO Finished QThread operationIndex = 0
> 2020-07-31 16:31:46 ri9 crazydiskmark[1322493] INFO Running Thread [1] Even? False
> 2020-07-31 16:31:46 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/seq1mq8t1write.sh /tmp/sdb1]
> --- Logging error ---
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
>     msg = self.format(record)
>   File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
>     return fmt.format(record)
>   File "/home/ryan/.local/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1115, in format
>     return logging.Formatter.format(self, record)
>   File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
>     record.message = record.getMessage()
>   File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "/home/ryan/.local/bin/crazydiskmark", line 16, in <module>
>     app.exec_()
>   File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 62, in threadFinished
>     self.signal.emit(self.bw_bytes)
>   File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 178, in receiveThreadfinish
>     self.logger.info('Receiving signal ok ', val)
> Message: 'Receiving signal ok '
> Arguments: ('187.49 MB/s',)
> 2020-07-31 16:31:53 ri9 crazydiskmark[1322493] INFO Finished QThread operationIndex = 1
> 2020-07-31 16:31:53 ri9 crazydiskmark[1322493] INFO Running Thread [2] Even? True
> 2020-07-31 16:31:53 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/seq1mq1t1read.sh /tmp/sdb1]
> --- Logging error ---
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
>     msg = self.format(record)
>   File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
>     return fmt.format(record)
>   File "/home/ryan/.local/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1115, in format
>     return logging.Formatter.format(self, record)
>   File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
>     record.message = record.getMessage()
>   File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "/home/ryan/.local/bin/crazydiskmark", line 16, in <module>
>     app.exec_()
>   File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 62, in threadFinished
>     self.signal.emit(self.bw_bytes)
>   File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 178, in receiveThreadfinish
>     self.logger.info('Receiving signal ok ', val)
> Message: 'Receiving signal ok '
> Arguments: ('175.05 MB/s',)
> 2020-07-31 16:32:06 ri9 crazydiskmark[1322493] INFO Finished QThread operationIndex = 2
> 2020-07-31 16:32:06 ri9 crazydiskmark[1322493] INFO Running Thread [3] Even? False
> 2020-07-31 16:32:06 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/seq1mq1t1write.sh /tmp/sdb1]
> --- Logging error ---
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
>     msg = self.format(record)
>   File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
>     return fmt.format(record)
>   File "/home/ryan/.local/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1115, in format
>     return logging.Formatter.format(self, record)
>   File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
>     record.message = record.getMessage()
>   File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "/home/ryan/.local/bin/crazydiskmark", line 16, in <module>
>     app.exec_()
>   File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 62, in threadFinished
>     self.signal.emit(self.bw_bytes)
>   File "/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/__init__.py", line 178, in receiveThreadfinish
>     self.logger.info('Receiving signal ok ', val)
> Message: 'Receiving signal ok '
> Arguments: ('187.1 MB/s',)
> 2020-07-31 16:32:12 ri9 crazydiskmark[1322493] INFO Finished QThread operationIndex = 3
> 2020-07-31 16:32:12 ri9 crazydiskmark[1322493] INFO Running Thread [4] Even? True
> 2020-07-31 16:32:12 ri9 crazydiskmark[1322493] INFO Running [/home/ryan/.local/lib/python3.8/site-packages/crazydiskmark/scripts/rnd4kq32t16read.sh /tmp/sdb1]
> ```

Hi, 

You are running crazydiskmark in mechanic disk. This app is to benchmark only ssd storages.

**Comment by fredcox** [comment]
Please, run crazydiskmark only in ssd. Thank you.
