### ISSUE TITLE
crash when start to benchmark

### ISSUE THREAD

**Issue by junyuewang** [fredcox/crazydiskmark#6]
it crashes immediately when press the 'start' button to benchmark. Thanks!
```
$ sudo python3 bin/crazydiskmark                
2020-08-29 14:35:21 localhost.localdomain __main__[14821] INFO Starting...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
2020-08-29 14:35:22 localhost.localdomain crazydiskmark[14821] INFO Desktop entry exists [bypass]
2020-08-29 14:35:30 localhost.localdomain crazydiskmark[14821] INFO Verify if dir /root is writable...
2020-08-29 14:35:30 localhost.localdomain crazydiskmark[14821] INFO /root is writable.
2020-08-29 14:35:30 localhost.localdomain crazydiskmark[14821] INFO Starting benchmark...
2020-08-29 14:35:30 localhost.localdomain crazydiskmark[14821] INFO Directory writable. OK [Starting Thread]
2020-08-29 14:35:30 localhost.localdomain crazydiskmark[14821] INFO Running Thread [0] Even? True
2020-08-29 14:35:30 localhost.localdomain crazydiskmark[14821] INFO Running [/usr/local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/scripts/seq1mq8t1read.sh /root]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/__init__.py", line 84, in run
    output = json.loads(subprocess.getoutput(cmd).encode('utf-8'))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/site-packages/coloredlogs-14.0-py3.6.egg/coloredlogs/__init__.py", line 1115, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "bin/crazydiskmark", line 16, in <module>
    app.exec_()
  File "/usr/local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/__init__.py", line 62, in threadFinished
    self.signal.emit(self.bw_bytes)
  File "/usr/local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/__init__.py", line 178, in receiveThreadfinish
    self.logger.info('Receiving signal ok ', val)
Message: 'Receiving signal ok '
Arguments: ('',)
2020-08-29 14:35:30 localhost.localdomain crazydiskmark[14821] INFO Finished QThread operationIndex = 0
2020-08-29 14:35:30 localhost.localdomain crazydiskmark[14821] INFO Running Thread [1] Even? False
2020-08-29 14:35:30 localhost.localdomain crazydiskmark[14821] INFO Running [/usr/local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/scripts/seq1mq8t1write.sh /root]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/__init__.py", line 84, in run
    output = json.loads(subprocess.getoutput(cmd).encode('utf-8'))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Aborted
```
some other info
```
$ fio --version
fio-3.22-23-gdb83
$ uname -a
Linux localhost.localdomain 5.4.38-1.fc28.lemote.mips64el #1 SMP PREEMPT Mon May 4 23:36:26 CST 2020 mips64 mips64 mips64 GNU/Linux
```

**Comment by fredcox** [comment]
> tton to benchmark. Thanks!

ok, man, you install pip package with sudo, and it is not recommended, please uninstall crazydiskmark with sudo pip3 uninstall crazydiskmark

Never install python packages with root or sudo, please. 


And now, install crazydiskmark with regular user (non-root), the command is: pip3 install crazydiskmark

Run crazydiskmark as normal user . Remember $HOME/.local/bin is must to be in your PATH environment variable. 

Please send me feedback about this. thank you.

**Comment by fredcox** [comment]
> $HOME/.local/bin i

Remember too; crazydiskmark is only to run with ssds, because mechanical hds is slowly and slowly.

**Comment by junyuewang** [comment]
Thanks for the help, but it still crashed. What I did was:
```
$sudo pip3 uninstall crazydiskmark
$sudo rm -rf crazydiskmark/
$git clone https://github.com/fredcox/crazydiskmark.git
$python3 setup.py install --user
$python3 ~/.local/bin/crazydiskmark
2020-08-29 15:59:21 localhost.localdomain __main__[17171] INFO Starting...
2020-08-29 15:59:22 localhost.localdomain crazydiskmark[17171] INFO Desktop entry exists [bypass]
2020-08-29 15:59:25 localhost.localdomain crazydiskmark[17171] INFO Verify if dir /home/junyue is writable...
2020-08-29 15:59:25 localhost.localdomain crazydiskmark[17171] INFO /home/junyue is writable.
2020-08-29 15:59:25 localhost.localdomain crazydiskmark[17171] INFO Starting benchmark...
2020-08-29 15:59:25 localhost.localdomain crazydiskmark[17171] INFO Directory writable. OK [Starting Thread]
2020-08-29 15:59:25 localhost.localdomain crazydiskmark[17171] INFO Running Thread [0] Even? True
2020-08-29 15:59:25 localhost.localdomain crazydiskmark[17171] INFO Running [/home/junyue/.local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/scripts/seq1mq8t1read.sh /home/junyue]
Traceback (most recent call last):
  File "/home/junyue/.local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/__init__.py", line 84, in run
    output = json.loads(subprocess.getoutput(cmd).encode('utf-8'))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/site-packages/coloredlogs-14.0-py3.6.egg/coloredlogs/__init__.py", line 1115, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/junyue/.local/bin/crazydiskmark", line 4, in <module>
    __import__('pkg_resources').run_script('crazydiskmark==0.2.50', 'crazydiskmark')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/home/junyue/.local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/EGG-INFO/scripts/crazydiskmark", line 16, in <module>
    app.exec_()
  File "/home/junyue/.local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/__init__.py", line 62, in threadFinished
    self.signal.emit(self.bw_bytes)
  File "/home/junyue/.local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/__init__.py", line 177, in receiveThreadfinish
    self.logger.info('Receiving signal ok ', val)
Message: 'Receiving signal ok '
Arguments: ('',)
2020-08-29 15:59:25 localhost.localdomain crazydiskmark[17171] INFO Finished QThread operationIndex = 0
2020-08-29 15:59:25 localhost.localdomain crazydiskmark[17171] INFO Running Thread [1] Even? False
2020-08-29 15:59:25 localhost.localdomain crazydiskmark[17171] INFO Running [/home/junyue/.local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/scripts/seq1mq8t1write.sh /home/junyue]
Traceback (most recent call last):
  File "/home/junyue/.local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg/crazydiskmark/__init__.py", line 84, in run
    output = json.loads(subprocess.getoutput(cmd).encode('utf-8'))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Aborted
```
When I tried pip3 install, it said carzydiskmark package requirement not met, so I had to install from git.

**Comment by junyuewang** [comment]
is my python3 version too old?
```
$ pip3 install --user crazydiskmark
Requirement already satisfied: crazydiskmark in /home/junyue/.local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg
crazydiskmark requires Python '>=3.8' but the running Python is 3.6.5
```

**Comment by fredcox** [comment]
> setup.py install --user

Please, you installing wrong again. 
Please, following scheme:

1. type: pip3 install crazydiskmark (no more necessary, no git clone, no sudo, please)
2. type crazydiskmark

**Comment by fredcox** [comment]
> is my python3 version too old?
> 
> ```
> $ pip3 install --user crazydiskmark
> Requirement already satisfied: crazydiskmark in /home/junyue/.local/lib/python3.6/site-packages/crazydiskmark-0.2.50-py3.6.egg
> crazydiskmark requires Python '>=3.8' but the running Python is 3.6.5
> ```

You need python 3.8 or later. Type: python3 --version to see your version

**Comment by junyuewang** [comment]
I tried on x86 machine, same error. Looks like python3 version too old is the cause. Many thanks again.

**Comment by junyuewang** [comment]
It works now, turned out to be that libaio has to be installed.
Thanks!

**Comment by junyuewang** [comment]
python 3.6 is ok

**Comment by fredcox** [comment]
> python 3.6 is ok

No.... Crazy DiskMark only work with python 3.8>=
